GlobalParameters:
  KeepBuildTmp: True
  AsmDebug: True
jobs:
    -
        kernel_include_regex: "split_embedding_backward_codegen_rowwise_adagrad_unweighted_kernel_cta_per_row_1"
        kernel_exclude_regex:
        kernel_iteration_range: "[1, [2-2]]"
        output_file: out_opt
        output_directory: split_embedding_bwd13_v23
        output_format: [json, csv, otf2, pftrace]
        truncate_kernels: true
        sys_trace: true # enable for pftrace and otf2
        advanced_thread_trace: true # enable for att and ui folder
        att_target_cu: 1
        att_shader_engine_mask: "0xf" # collect one CU from 4 SEs
        att_simd_select: "0xf" # col+lect 4 SIMDs on single CU
        att_buffer_size: "0x6000000"
